apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fliperama-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/projeto1.git
    path: fliperama
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# https://hub.docker.com/r/magicalyak/docker-games/tags
